### ISSUE TITLE
TapJoy mediation error in Unity

### ISSUE THREAD

**Issue by iseeall** [googleads/googleads-mobile-android-mediation#10]
Hello, I'm trying to mediate TapJoy from the Unity AdMob plugin. Getting the following error in logcat.
What's **mraid.js**, is it missing in the TapJoy sdk or the adapter?

```
07-01 18:14:17.113: I/Ads(26452): Instantiating mediation adapter: com.google.ads.mediation.tapjoy.TapjoyAdapter
07-01 18:14:17.129: W/Ads(26452): Server parameters: {"gwhirl_share_location":"1","placementName":"Android AdMob Mediated Interstitial","sdkKey":"uE4lKQTXTXWpE2ZsvA7W5AECFbPJg55cztUELHN3miCbFBYpGb-OK4W5KGm8"}
07-01 18:14:17.191: D/dalvikvm(26452): GC_FOR_ALLOC freed 500K, 14% free 11585K/13447K, paused 57ms, total 57ms
07-01 18:14:17.207: I/TapjoyAdapter(26452): Connecting to Tapjoy for Tapjoy-AdMob adapter
07-01 18:14:17.277: D/dalvikvm(26452): GC_FOR_ALLOC freed 152K, 14% free 11677K/13447K, paused 68ms, total 69ms
07-01 18:14:17.293: I/Ads(26452): Trying mediation network: https://googleads.g.doubleclick.net/aclk?sa=L&ai=CiPyDWrxXWZzhDoiKywWNsbEw-cnapgXR74W6kgEAEAgg_u60PmCEleyF3B2pAgAAAACAhC5BqAMBqgQgT9Dj6zSN9VLefMYf3ZpTJ-D27Dl0sC50i6A_z45GjaKQBgHABguAB4H4qTCYBwHSCAUIgGEQAQ&num=1&cid=CAASBORoRec&sig=AOD64_0VhhVvin_r_UqloI6Y6e3dNJfLmg&adurl=http://example.com
07-01 18:14:17.605: W/ResourceType(26452): No package identifier when getting value for resource number 0x00000000
07-01 18:14:17.629: W/System.err(26452): java.io.FileNotFoundException: js/mraid.js
07-01 18:14:17.629: W/System.err(26452): 	at android.content.res.AssetManager.openAsset(Native Method)
07-01 18:14:17.629: W/System.err(26452): 	at android.content.res.AssetManager.open(AssetManager.java:315)
07-01 18:14:17.637: W/System.err(26452): 	at android.content.res.AssetManager.open(AssetManager.java:289)
07-01 18:14:17.637: W/System.err(26452): 	at com.tapjoy.TapjoyUtil.copyTextFromJarIntoString(SourceFile:583)
07-01 18:14:17.637: W/System.err(26452): 	at com.tapjoy.TapjoyConnectCore.j(SourceFile:9308)
07-01 18:14:17.637: W/System.err(26452): 	at com.tapjoy.TapjoyConnectCore.<init>(SourceFile:4697)
07-01 18:14:17.637: W/System.err(26452): 	at com.tapjoy.TapjoyConnectCore.requestTapjoyConnect(SourceFile:269)
07-01 18:14:17.637: W/System.err(26452): 	at com.tapjoy.internal.dv.a(SourceFile:77)
07-01 18:14:17.637: W/System.err(26452): 	at com.tapjoy.internal.dw.a(SourceFile:9)
07-01 18:14:17.637: W/System.err(26452): 	at com.tapjoy.internal.dw$1.a(SourceFile:15)
07-01 18:14:17.637: W/System.err(26452): 	at com.tapjoy.internal.fe.b(SourceFile:1156)
07-01 18:14:17.637: W/System.err(26452): 	at com.tapjoy.internal.dw.a(SourceFile:22)
07-01 18:14:17.637: W/System.err(26452): 	at com.tapjoy.Tapjoy.connect(SourceFile:96)
07-01 18:14:17.637: W/System.err(26452): 	at com.google.ads.mediation.tapjoy.TapjoyAdapter.requestInterstitialAd(TapjoyAdapter.java:146)
07-01 18:14:17.637: W/System.err(26452): 	at com.google.android.gms.internal.zzkh.zza(Unknown Source)
07-01 18:14:17.637: W/System.err(26452): 	at com.google.android.gms.internal.zzkb$zza.onTransact(Unknown Source)
07-01 18:14:17.637: W/System.err(26452): 	at android.os.Binder.transact(Binder.java:326)
07-01 18:14:17.637: W/System.err(26452): 	at com.google.android.gms.ads.internal.mediation.client.g.a(:com.google.android.gms.DynamiteModulesA:115)
07-01 18:14:17.637: W/System.err(26452): 	at com.google.android.gms.ads.internal.mediation.g.a(:com.google.android.gms.DynamiteModulesA:117)
07-01 18:14:17.637: W/System.err(26452): 	at com.google.android.gms.ads.internal.mediation.e.run(:com.google.android.gms.DynamiteModulesA:34)
07-01 18:14:17.645: W/System.err(26452): 	at android.os.Handler.handleCallback(Handler.java:615)
07-01 18:14:17.645: W/System.err(26452): 	at android.os.Handler.dispatchMessage(Handler.java:92)
07-01 18:14:17.645: W/System.err(26452): 	at android.os.Looper.loop(Looper.java:137)
07-01 18:14:17.645: W/System.err(26452): 	at android.app.ActivityThread.main(ActivityThread.java:4895)
07-01 18:14:17.645: W/System.err(26452): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-01 18:14:17.645: W/System.err(26452): 	at java.lang.reflect.Method.invoke(Method.java:511)
07-01 18:14:17.645: W/System.err(26452): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
07-01 18:14:17.645: W/System.err(26452): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
07-01 18:14:17.652: W/System.err(26452): 	at dalvik.system.NativeStart.main(Native Method)
07-01 18:14:17.652: W/ResourceType(26452): No package identifier when getting value for resource number 0x00000000
07-01 18:14:17.652: E/TapjoyLog:TapjoyConnect(26452): Type=INTEGRATION_ERROR;Message=ClassNotFoundException: mraid.js was not found.
07-01 18:14:17.652: D/TapjoyAdapter(26452): Tapjoy failed to connect
```

I followed the guide here:
https://developers.google.com/admob/android/mediation/tapjoy
Downloaded adapter from here:
https://bintray.com/google/mobile-ads-adapters-android/download_file?file_path=com%2Fgoogle%2Fads%2Fmediation%2Ftapjoy%2F11.11.0.0%2Ftapjoy-11.11.0.0.aar
and took **tapjoyconnectlibrary.jar** from here:
https://ltv.tapjoy.com/d/sdks/android/download

**Comment by iseeall** [comment]
![tapjoy](https://user-images.githubusercontent.com/8617651/27763579-b09dab94-5e8e-11e7-929e-884ef193402c.PNG)

**Comment by iseeall** [comment]
Strangely the error disappeared by itself after a few hours, and TapJoy videos started showing. Weird.

**Comment by ericleich** [comment]
Glad it worked itself out, closing this ticket.
