### ISSUE TITLE
No advertisements are available for your current bid. Please try again later.

### ISSUE THREAD

**Issue by nazmulkp** [googleads/googleads-mobile-android-mediation#108]
I got this crash as result this my application getting shut down. a few users reporting issue too, 

 ```
01-03 07:39:08.778 26919-26919/com.nazmul.aznazgame.bitlife E/Vungle: Failed to download assets for DEFAULT-1887519. Cause:
    com.vungle.warren.error.VungleException: No advertisements are available for your current bid. Please try again later.
        at com.vungle.warren.Vungle$7.onResponse(Vungle.java:1128)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
01-03 07:39:08.778 26919-26919/com.nazmul.aznazgame.bitlife E/com.vungle.warren.tasks.DownloadJob: scheduleJob: loadAd onError: 1
```

**Comment by palrahul** [comment]
@nazmulkp VungleException in Vungle's SDK is handled exception and returned as a Throwable error and should by itself not cause any crash. The SDK returns a Throwable error, which if developers want can use specific Codes to take specific actions, find the actual cause, or just ignore it.
More details at Vungle's Sample app:
https://github.com/Vungle/Android-SDK/blob/master/app/src/main/java/com/publisher/sample/MainActivity.java#L164

Please let us know if this helps in your case.
