### ISSUE TITLE
Unity Mediation - NullPointerException on show interstitial

### ISSUE THREAD

**Issue by tankiettc** [googleads/googleads-mobile-android-mediation#127]
I called show interstitial and got this bug, the ad did not show. I was trying use test mediation app (https://developers.google.com/admob/android/mediation-test-suite)  but got the same result. Hope you can help me resolve this issue. 
Thank you.

Both my devices:
-Asus Zenfone 3 Max
-Xiaomi Xiaomi Redmi 6 Pro

`04-05 10:12:49.028 5328-5328/? E/Ads: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.google.ads.mediation.unity.UnityAdapter.showInterstitial(UnityAdapter.java:286)
        at com.google.android.gms.internal.ads.zzanm.showInterstitial(Unknown Source)
        at com.google.android.gms.internal.ads.zzamu.dispatchTransaction(Unknown Source)
        at com.google.android.gms.internal.ads.zzfn.onTransact(Unknown Source)
        at android.os.Binder.transact(Binder.java:387)
        at oh.b(:com.google.android.gms.dynamite_adsdynamite@16089051@16.0.89 (040408-239467275):14)
        at com.google.android.gms.ads.internal.mediation.client.g.b(:com.google.android.gms.dynamite_adsdynamite@16089051@16.0.89 (040408-239467275):27)
        at com.google.android.gms.ads.nonagon.render.ar.a(Unknown Source)
        at com.google.android.gms.ads.nonagon.shim.s.P(:com.google.android.gms.dynamite_adsdynamite@16089051@16.0.89 (040408-239467275):65)
        at com.google.android.gms.ads.nonagon.shim.j.P(:com.google.android.gms.dynamite_adsdynamite@16089051@16.0.89 (040408-239467275):13)
        at com.google.android.gms.ads.internal.client.an.a(:com.google.android.gms.dynamite_adsdynamite@16089051@16.0.89 (040408-239467275):129)
        at oi.onTransact(:com.google.android.gms.dynamite_adsdynamite@16089051@16.0.89 (040408-239467275):4)
        at android.os.Binder.transact(Binder.java:387)
        at com.google.android.gms.internal.ads.zzfm.zza(Unknown Source)
        at com.google.android.gms.internal.ads.zzzk.showInterstitial(Unknown Source)
        at com.google.android.gms.internal.ads.zzabb.show(Unknown Source)
        at com.google.android.gms.ads.InterstitialAd.show(Unknown Source)
        at org.cocos2dx.cpp.kd.admob.AdmobHelper.showInterstitial(AdmobHelper.java:267)
        at org.cocos2dx.cpp.kd.admob.AdmobHelper.access$2400(AdmobHelper.java:32)
        at org.cocos2dx.cpp.kd.admob.AdmobHelper$4.run(AdmobHelper.java:476)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5451)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by tankiettc** [comment]
I figure out the issue. Just comment out the line implement mediation in gradle file
`//    implementation 'com.google.ads.mediation:unity:3.0.0.2'`
Then download files at https://github.com/googleads/googleads-mobile-android-mediation/tree/master/ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity
and copy to your project.
