### ISSUE TITLE
 Fail to instantiate adapter com.google.ads.mediation.chartboost.ChartboostAdapter

### ISSUE THREAD

**Issue by mycks** [googleads/googleads-mobile-android-mediation#13]
07-26 18:31:24.945 25813-27077/? W/Ads: Fail to instantiate adapter com.google.ads.mediation.chartboost.ChartboostAdapter
                                        android.os.RemoteException
                                            at com.google.android.gms.internal.zzup.zzak(Unknown Source)
                                            at com.google.android.gms.internal.zzup.zzaj(Unknown Source)
                                            at com.google.android.gms.internal.zzup.zzah(Unknown Source)
                                            at com.google.android.gms.internal.zzacs.zzav(Unknown Source)
                                            at com.google.android.gms.internal.zzadw.zzbd(Unknown Source)
                                            at com.google.android.gms.internal.zzafq.run(Unknown Source)
                                            at com.google.android.gms.internal.zzagv.call(Unknown Source)
                                            at com.google.android.gms.internal.zzagw.run(Unknown Source)
                                            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                            at java.lang.Thread.run(Thread.java:818)

Cannot instantiate this adapter, I have been on the libs folder below.Really don't know where the problem is.Hope you can help me have a look.thank you

**Comment by ericleich** [comment]
This means that the Chartboost adapter is not part of the app package. Did you include the Chartboost adapter as mentioned in [this guide](https://developers.google.com/admob/android/mediation/chartboost#step_3_import_the_chartboost_sdk_and_adapter)?

**Comment by danielp299** [comment]
The error may be related to the use of the new API in 2019 has no support

try using RewardBasedVideoAd instead of RewardedAd
