### ISSUE TITLE
[BUG?] FacebookAdapter findClosestSize method always returns 'null'

### ISSUE THREAD

**Issue by tominou** [googleads/googleads-mobile-android-mediation#140]
com.facebook.android:audience-network-sdk:5.3.0
com.google.ads.mediation:facebook:5.3.0.0
com.google.android.gms:play-services-ads:17.2.1

FacebookAdapter never returns banners because `findClosestSize` always returns `null`

From adb logcat:
```
05-26 08:41:13.211  6557  6557 I FacebookAdapter: Potential ad sizes: [FULLx50_as, FULLx90_as, FULLx250_as]
05-26 08:41:13.211  6557  6557 W FacebookAdapter: The input ad size 393x50_as is not supported at this moment.
```

**Comment by stowy** [comment]
Hi, thanks for posting, can you share your client code for requesting the ad? What ad size are you specifying?

**Comment by tominou** [comment]
Hi Stowy,

I specify SMART_BANNER ad size. If i switch to BANNER, ads are showing fine.
Here is the code: https://github.com/ratson/cordova-plugin-admob-free/tree/master/src/android

Thank you for your time ^^

**Comment by rodrigograca31** [comment]
I'm having the same issue:
I'm using `SMART_BANNER` and [I see many requests but 0% match rate as I describe here ](https://github.com/ratson/cordova-plugin-admob-free/issues/346#issuecomment-500638325)and I think its because of this "bug":
```
06-18 21:33:14.845 19468 19468 I FacebookAdapter: Potential ad sizes: [FULLx50_as, FULLx90_as, FULLx250_as]
06-18 21:33:14.845 19468 19468 W FacebookAdapter: The input ad size 360x50_as is not supported at this moment.
```

if I use `BANNER` I see this:
```
06-18 22:08:57.916  4266  4266 I FacebookAdapter: Potential ad sizes: [320x50_as, 320x90_as, 320x250_as]
06-18 22:08:57.916  4266  4266 I FacebookAdapter: Found closest ad size: 320x50_as
06-18 22:08:58.037  4266  4266 E Ads     :      at com.google.ads.mediation.facebook.FacebookInitializer.initialize(FacebookInitializer.java:51)
06-18 22:08:58.037  4266  4266 E Ads     :      at com.google.ads.mediation.facebook.FacebookInitializer.initialize(FacebookInitializer.java:33)
06-18 22:08:58.037  4266  4266 E Ads     :      at com.google.ads.mediation.facebook.FacebookAdapter.requestBannerAd(FacebookAdapter.java:163)
```

I still dont see ads but I think that's because Facebook has no ads for me.... Tried on 3 phones though........

**Comment by rodrigograca31** [comment]
@tominou do you think my problem with 0% match rate is because I use `SMAR_BANNER`?

**Comment by tominou** [comment]
@rodrigograca31 Yes Im pretty sure it is. But FB should support SMART_BANNER, it did work fine until recent sdk releases.

**Comment by rodrigograca31** [comment]
Oh, ok. Thanks @tominou !
Let's hope it gets fixed. maybe I will dig deeper to find a sdk version that works....

I've now tried in a fourth phone and still no ads while using `BANNER` but its probably because they are all in the same network and etc....
I should also configure mediation for my interstitial ad and that might help me debug stuff....

**Comment by tominou** [comment]
In your logs, size is not an issue when you use BANNER, but you still got some errors that may prevent it to work:
`06-18 22:08:58.037  4266  4266 E Ads     :      at com.google.ads.mediation.facebook.FacebookInitializer.initialize(FacebookInitializer.java:51)
06-18 22:08:58.037  4266  4266 E Ads     :      at com.google.ads.mediation.facebook.FacebookInitializer.initialize(FacebookInitializer.java:33)
06-18 22:08:58.037  4266  4266 E Ads     :      at com.google.ads.mediation.facebook.FacebookAdapter.requestBannerAd(FacebookAdapter.java:163)`

**Comment by rodrigograca31** [comment]
@tominou also, in case you didn't notice your plugin uses 5.3.0.0 and 5.4.0.0 was just released.
Not sure if it fixes it though... but there's also 5.3.1.x....

**Comment by rodrigograca31** [comment]
wait.... were those erros? I was using `adb logcat | grep -i facebook` so didnt see the whole output but maybe they are.....!

**Comment by rodrigograca31** [comment]
Seems 5.4.0 also doesnt support `SMART_BANNER` .... 
[Also seems there was changes in](https://developers.google.com/admob/android/rel-notes) `com.google.android.gms:play-services-ads:17.2.0` related to mediation.

```
Mediation: Added a new set of mediation adapter APIs that support initialization. Adapters implementing the new API implement the Adapter class.
```

**Comment by rodrigograca31** [comment]
@tominou you were correct! 
changing to 'BANNER' makes it work. (Even though I would prefer 'SMART_BANNER' because its probably better for advertisers, so its probably brings better revenue....)

you were also right about me having a bug. it was #133 .

@tominou Thanks a lot for your help!

**Comment by dfretes** [comment]
I'm also having the same issue with 'SMART_BANNER' and the facebook adapter. I hope this gets fixed since SMART_BANNERs have a higher eCPM overall.  

There used to be a clever function on the Adapter that would match the requested Admob Ad size to the closest Ad size on FAN SDK.

Regards!

**Comment by TomTasche** [comment]
According to the changelog, this was fixed: "Fixed an issue that caused Smart Banner Ad requests to fail." - https://developers.google.com/admob/android/mediation/facebook#facebook-android-mediation-adapter-changelog

**Comment by foreza** [comment]
Thank you all for filing and working through this issue a couple years ago!
We're currently working through our issue backlog and are closing older reports.

If you are still experiencing other problems or have questions about the latest versions of our mediation adapters (like Meta), please **file a new issue** and provide all the information requested in our new issue template (work in progress).
