### ISSUE TITLE
MoPub Mediation Adapter : Null Point Access Issue

### ISSUE THREAD

**Issue by shomin1983** [googleads/googleads-mobile-android-mediation#142]
Hi,
I found some crash issue by MoPub Mediation Adpater 5.4.1.2.
`
at com.mopub.mobileads.dfp.adapters.MoPubAdapter$4.onInitializationFinished(MoPubAdapter.java:320)
       at com.google.ads.mediation.mopub.MoPubSingleton$1.onInitializationFinished(MoPubSingleton.java:92)
       at com.mopub.common.MoPub$1.run(MoPub.java:358)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7058)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
`

After checking codes in adapter, the mMoPubView may be set to null if onDestroy() is called, but didn't check mMoPubView is null before calling mMoPubView.loadAd().

Please help to fix NPE issue.

**Comment by spilaka** [comment]
@shomin1983  Are you still facing this issue ?

**Comment by foreza** [comment]
Hi [shomin1983](https://github.com/shomin1983) - thank you for filing this issue a couple years ago!
We're currently working through our issue backlog and are closing older reports.

As it has been over a year with no updates (and given quite a _few_ changes to Mopub...), I'm closing this issue. 

If you are still experiencing other problems or have questions  about the latest versions of our mediation adapters, please **file a new issue** and provide all the information requested in our new issue template (work in progress).
