### ISSUE TITLE
MoPubAdapter.onDestroy is not called after calling AdView.destroy()

### ISSUE THREAD

**Issue by footprint** [googleads/googleads-mobile-android-mediation#169]
hi, we integrate MoPub with admob mediation, and we found a bug, MoPubAdapter.onDestroy method is not called after calling AdView.destroy(),it causes memory leaks & crash:

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/1246678/62856174-c3080380-bd26-11e9-9131-788a9d8f7657.png">

**Comment by ogrenichv** [comment]
Having the same issue, MoPub 5.17, AdMob 20.2, latest version of MoPub adapter
```
 E/ActivityThread: Activity MainActivity has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@ea2ae55 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity MainActivity has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@ea2ae55 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1603)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1539)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1512)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1500)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:627)
        at com.mopub.mobileads.MoPubView.registerScreenStateBroadcastReceiver(MoPubView.java:182)
        at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:144)
        at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:120)
        at com.mopub.mobileads.dfp.adapters.MoPubAdapter.requestBannerAd(MoPubAdapter.java:318)
        at com.google.android.gms.internal.ads.zzaon.zza(com.google.android.gms:play-services-ads-lite@@19.8.0:52)
        at com.google.android.gms.internal.ads.zzanr.zza(com.google.android.gms:play-services-ads-lite@@19.8.0:56)
        at com.google.android.gms.internal.ads.zzgy.onTransact(com.google.android.gms:play-services-ads-base@@19.8.0:13)
        at android.os.Binder.transact(Binder.java:925)
        at gc.bb(:com.google.android.gms.policy_ads_fdr_dynamite@210402101@210402101057.356914649.356914649:2)
        at com.google.android.gms.ads.internal.mediation.client.e.j(:com.google.android.gms.policy_ads_fdr_dynamite@210402101@210402101057.356914649.356914649:0)
        at com.google.android.gms.ads.nonagon.render.af.a(:com.google.android.gms.policy_ads_fdr_dynamite@210402101@210402101057.356914649.356914649:14)
        at com.google.android.gms.ads.nonagon.render.do.a(Unknown Source:0)
        at com.google.android.gms.ads.nonagon.util.concurrent.s.call(Unknown Source:0)
        at zu.a(:com.google.android.gms.policy_ads_fdr_dynamite@210402101@210402101057.356914649.356914649:0)
        at zg.run(:com.google.android.gms.policy_ads_fdr_dynamite@210402101@210402101057.356914649.356914649:3)
        at zv.run(:com.google.android.gms.policy_ads_fdr_dynamite@210402101@210402101057.356914649.356914649:0)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at qr.a(:com.google.android.gms.policy_ads_fdr_dynamite@210402101@210402101057.356914649.356914649:0)
        at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@210402101@210402101057.356914649.356914649:1)
        at qr.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@210402101@210402101057.356914649.356914649:0)
```

**Comment by joshh-devrel** [comment]
Closed as this is obsolete - [MoPub has sunset](https://developers.google.com/admob/android/mediation/mopub).
