### ISSUE TITLE
NPE in InMobiUnifiedNativeAdMapper

### ISSUE THREAD

**Issue by SwagatoMondal** [googleads/googleads-mobile-android-mediation#214]
Hi Guys,

I'm a developer from InMobi's Android team, and our pub has complained of the following crash. Please help us in resolving this, also this file seems to have been created and pushed by you guys.
**File** : https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getWidth()' on a null object reference
       at com.google.ads.mediation.inmobi.InMobiUnifiedNativeAdMapper$1.onGlobalLayout(InMobiUnifiedNativeAdMapper.java:144)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1013)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2692)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7832)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
Let us know if any other information is required.

**Comment by joshuajplagonera** [comment]
Hi @SwagatoMondal 
Thank you for reporting this crash. We have pushed out a fix for this which is scheduled to go out with the next release of the adapter.
