### ISSUE TITLE
NPE on Vungle SDK initialization

### ISSUE THREAD

**Issue by abgita** [googleads/googleads-mobile-android-mediation#222]
### Stacktrace:

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Collection.size()' on a null object reference
       at com.vungle.warren.Vungle.isInitialized(Vungle.java:611)
       at com.vungle.warren.Vungle.canPlayAd(Vungle.java:693)
       at com.google.ads.mediation.vungle.VungleMediationAdapter.onInitializeSuccess(VungleMediationAdapter.java:199)
       at com.google.ads.mediation.vungle.VungleInitializer$2.run(VungleInitializer.java:98)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7258)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`

### Devices:

- Galaxy J7 Prime
- Galaxy J2 Prime
- Galaxy A30
- Motorola one
- Moto E (4) Plus
- Moto E (5)
- Xiaomi Mi A2 
- Positivo BGH G1101T

**Comment by abgita** [comment]
### Google Play services SDK:
_com.google.firebase:firebase-core:17.2.1
com.google.firebase:firebase-ads:18.3.0
com.google.firebase:firebase-analytics:17.2.1_

### Mediation:
_com.google.ads.mediation:vungle:6.4.11.1_
