### ISSUE TITLE
Facebook adapter and WebView data directory

### ISSUE THREAD

**Issue by dfretes** [googleads/googleads-mobile-android-mediation#223]
It seems that when using mediation, FAN initializes its WebView on the same directory as the main Application's process. With changes in Android P, this crashes the application. 

> Fatal Exception: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
       at org.chromium.android_webview.AwBrowserProcess.b(AwBrowserProcess.java:11)
       at Um.g(Um.java:27)
       at Tm.run(Tm.java:2)
       at bm0.f(bm0.java:11)
       at am0.run(am0.java:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7099)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

> main
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:447)
       at java.util.concurrent.FutureTask.get(FutureTask.java:205)
       at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:23)
       at com.crashlytics.android.core.CrashlyticsController.a(CrashlyticsController.java:62)
       at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:2)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:17)
       at com.facebook.ads.redexgen.X.F4.A03(F4.java:24426)
       at com.facebook.ads.redexgen.X.F4.uncaughtException(F4.java:24448)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
       at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)

**Comment by foreza** [comment]
Hi [dfretes](https://github.com/dfretes) - thank you for filing this issue a couple years ago!
We're currently working through our issue backlog and are closing older reports.

It's very likely that the latest version of the FAN (now Meta!) SDK / corresponding adapter have already addressed this specific crash:
https://developers.google.com/admob/android/mediation/meta#step_3_import_the_meta_audience_network_sdk_and_adapter
As it has been over a year with no updates, I'm closing this issue. 

If you are still experiencing other problems or have questions about the latest versions of the Meta mediation adapter, please **file a new issue** and provide all the information requested in our new issue template. (work in progress for those!)
