### ISSUE TITLE
Mediation Test Suite Crash

### ISSUE THREAD

**Issue by mbpictures** [googleads/googleads-mobile-android-mediation#227]
Hi!

I'm currently developing a plugin for UnrealEngine4 which supports GoogleAds and mediation. I'm trying to launch the Test Suite using this code
`MediationTestSuite.launch(GameActivity.this);`
but the app crashes instantly with this Exception
`2020-03-09 00:47:21.436 12666-12666/de.mariusbutz.uegoogleadsdemo E/AndroidRuntime: FATAL EXCEPTION: MainThread-UE4
    Process: de.mariusbutz.uegoogleadsdemo, PID: 12666
    java.lang.AssertionError: AssertionError (GSON 2.8.5): java.lang.NoSuchFieldException: ERROR
        at com.google.gson.f.a(Unknown Source:54)
        at com.google.gson.f.a(Unknown Source:4)
        at com.google.gson.f.a(Unknown Source:9)
        at com.google.android.ads.mediationtestsuite.utils.f.a(Unknown Source:19)
        at com.google.android.ads.mediationtestsuite.utils.f.a(Unknown Source:183)
        at com.google.android.ads.mediationtestsuite.dataobjects.DataStore.h(Unknown Source:26)
        at com.google.android.ads.mediationtestsuite.activities.HomeActivity.onCreate(Unknown Source:83)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: ERROR
        at com.google.gson.internal.bind.i$a.<init>(Unknown Source:87)
        at com.google.gson.internal.bind.TypeAdapters$30.a(Unknown Source:29)
        at com.google.gson.f.a(Unknown Source:74)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:42)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:123)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:22)
        at com.google.gson.f.a(Unknown Source:74)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:42)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:123)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:22)
        at com.google.gson.f.a(Unknown Source:74)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.a(Unknown Source:26)
        at com.google.gson.f.a(Unknown Source:74)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:42)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:123)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:22)
        at com.google.gson.f.a(Unknown Source:74)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.a(Unknown Source:26)
        at com.google.gson.f.a(Unknown Source:74)
        at com.google.gson.f.a(Unknown Source:16)
        at com.google.gson.f.a(Unknown Source:4) 
        at com.google.gson.f.a(Unknown Source:9) 
        at com.google.android.ads.mediationtestsuite.utils.f.a(Unknown Source:19) 
        at com.google.android.ads.mediationtestsuite.utils.f.a(Unknown Source:183) 
        at com.google.android.ads.mediationtestsuite.dataobjects.DataStore.h(Unknown Source:26) 
        at com.google.android.ads.mediationtestsuite.activities.HomeActivity.onCreate(Unknown Source:83) 
        at android.app.Activity.performCreate(Activity.java:7183) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: java.lang.NoSuchFieldException: ERROR
        at java.lang.Class.getField(Class.java:1601)
        at com.google.gson.internal.bind.i$a.<init>(Unknown Source:34)
        at com.google.gson.internal.bind.TypeAdapters$30.a(Unknown Source:29) 
        at com.google.gson.f.a(Unknown Source:74) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:42) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:123) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:22) 
        at com.google.gson.f.a(Unknown Source:74) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:42) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:123) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:22) 
        at com.google.gson.f.a(Unknown Source:74) 
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.a(Unknown Source:26) 
        at com.google.gson.f.a(Unknown Source:74) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:42) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:123) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:22) 
        at com.google.gson.f.a(Unknown Source:74) 
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.a(Unknown Source:26) 
        at com.google.gson.f.a(Unknown Source:74) 
        at com.google.gson.f.a(Unknown Source:16) 
        at com.google.gson.f.a(Unknown Source:4) 
        at com.google.gson.f.a(Unknown Source:9) 
        at com.google.android.ads.mediationtestsuite.utils.f.a(Unknown Source:19) 
        at com.google.android.ads.mediationtestsuite.utils.f.a(Unknown Source:183) 
        at com.google.android.ads.mediationtestsuite.dataobjects.DataStore.h(Unknown Source:26) 
        at com.google.android.ads.mediationtestsuite.activities.HomeActivity.onCreate(Unknown Source:83) 
        at android.app.Activity.performCreate(Activity.java:7183) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) `

Do you have any idea how to fix this?

**Comment by mbpictures** [comment]
I fixed it by adding these properties to my gradle:
`buildTypes {
	release {
		debuggable true
		minifyEnabled false
	}
}`
