### ISSUE TITLE
MediationTestSuite.launch() 1.3.0 crash

### ISSUE THREAD

**Issue by kmityakov** [googleads/googleads-mobile-android-mediation#237]
Here's the exception I get when I try to launch MediationTestSuite 1.3.0. Have to fallback to 1.2.2 for now.
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
        at com.google.android.ads.mediationtestsuite.dataobjects.ConfigurationItem.<init>(ConfigurationItem.java:68)
        at com.google.android.ads.mediationtestsuite.dataobjects.AdUnit.<init>(AdUnit.java:63)
        at com.google.android.ads.mediationtestsuite.utils.MediationConfigClient.getAdUnitsFromCldJson(MediationConfigClient.java:146)
        at com.google.android.ads.mediationtestsuite.utils.MediationConfigClient$1.onResponse(MediationConfigClient.java:110)
        at com.google.android.ads.mediationtestsuite.utils.MediationConfigClient$1.onResponse(MediationConfigClient.java:106)
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

I use the following ads related dependencies:
`implementation 'com.google.firebase:firebase-ads:18.3.0'` (Checked on `19.0.1` as well)
`implementation 'com.google.ads.mediation:facebook:5.7.1.1'`
`implementation 'com.google.ads.mediation:inmobi:9.0.2.0'`

**Comment by stowy** [comment]
Thanks for reporting @kmityakov. This issue has come up internally and it will be fixed in the next release of the test suite. In the meantime I recommend sticking with 1.2.2 for now.

**Comment by kmityakov** [comment]
@stowy Thanks for the info. I'd keep this open before the new release comes out if you don't mind.

**Comment by dasebasto** [comment]
Same issue here.
