### ISSUE TITLE
Possible error in FacebookAdapter 5.8.0

### ISSUE THREAD

**Issue by ogrenichv** [googleads/googleads-mobile-android-mediation#240]
I think that there is an error in Facebook adapter related to mapping Facebook native ad to the mapper.
Please take a loot at mapNativeAd method in FacebookAdapter.java class. When isNativeBanner is true it maps data from mNativeBannerAd only. But when isNativeBanner is false it maps headline, body text, images from mNativeAd and, for some reason, it maps icon from mNativeBannerAd. It looks like it should map icon from mNativeAd but not from mNativeBannerAd.
We are having crashes because of this:
```
Non-fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.ads.NativeAdBase$Image com.facebook.ads.NativeAdBase.getAdIcon()' on a null object reference
       at Message.Attempt to invoke virtual method 'com.facebook.ads.NativeAdBase$Image com.facebook.ads.NativeAdBase.getAdIcon()' on a null object reference(NativeAdBase.java)
       at Message.Attempt to invoke virtual method 'com.facebook.ads.NativeAdBase$Image com.facebook.ads.NativeAdBase.getAdIcon()' on a null object reference(NativeAdBase.java)
       at com.google.ads.mediation.facebook.FacebookAdapter$AppInstallMapper.mapNativeAd + 1006(FacebookAdapter.java:1006)
       at com.google.ads.mediation.facebook.FacebookAdapter$NativeListener.onAdLoaded + 779(FacebookAdapter.java:779)
       at com.facebook.ads.redexgen.X.YF.A01 + 65983(YF.java:65983)
       at com.facebook.ads.redexgen.X.21.run + 4734(21.java:4734)
       at android.os.Handler.handleCallback + 883(Handler.java:883)
       at android.os.Handler.dispatchMessage + 100(Handler.java:100)
```

I tried to debug and it seems that the icon present in mNativeAd but doesn't present in mNativeBannerAd.

Could you please clarify is it a bug or it is intended and icon should be mapped from different class?

**Comment by brownEugene** [comment]
The problem is an error, it seems that it should map icon from mNativeAd but not from mNativeBannerAd.
It will be updated on next adapter release

**Comment by kozaxinan** [comment]
We also have similar null pointer exception after updating from 5.6.1 to 5.8.0

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.ads.NativeAdBase$Image com.facebook.ads.NativeAdBase.getAdIcon()' on a null object reference
       at com.google.ads.mediation.facebook.FacebookAdapter$AppInstallMapper.mapNativeAd(FacebookAdapter.java:939)
       at com.google.ads.mediation.facebook.FacebookAdapter$NativeListener.onAdLoaded(FacebookAdapter.java:712)
       at com.facebook.ads.redexgen.X.YF.A01(YF.java:65983)
       at com.facebook.ads.redexgen.X.21.run(21.java:4734)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8147)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

from what I find, problem is introduced in this change.

https://github.com/googleads/googleads-mobile-android-mediation/commit/fe86f0ed7c243a3306ddfc2eca741352dc6febde#diff-09e2a695aa074530dbfe64c40bd40398R929

It was using mNativeAd but now it uses mNaviteBannerAd which is null at that point.

If you need any other information, I can provide. 
I dont have repo to produce issue, it crashes for %30 of our users. We halted release to prevent issue to spread.

**Comment by kozaxinan** [comment]
This issue seems like a simple error that could be fixed by a static code analysis tool. I wonder if there are any setup for this repo. Lots of application use this code to earn money, I expect this library doesnt crash with this kind of simple issues.

**Comment by joshuajplagonera** [comment]
Hi All
The fix should be live now with the Facebook Android adapter version 5.8.0.2 release.

**Comment by kozaxinan** [comment]
Thank you for fix and quick response. 

I am curious about how to prevent similar issues in the future. Refactoring code with wrong field names could break library again. And the fix for issue doesn't include any test or any other checks. Is there any plan to add integration test or code analysis to catch this kind of issue before release?
