### ISSUE TITLE
FacebookAdapter ClassCastException

### ISSUE THREAD

**Issue by alexskobozev** [googleads/googleads-mobile-android-mediation#314]
In FacebookAdapter NativeAd trackViews there is no check for class type casting:

https://github.com/googleads/googleads-mobile-android-mediation/blob/b73fbd89e1375cd12a48b8cb381d450e35437ea5/ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java#L927-L933

It can lead to ClassCastExceptions because it is possible for AdMob to hold no-ImageView classes as icons, and there is no special requirements for ImageView in AdMob documentation: https://developers.google.com/android/reference/com/google/android/gms/ads/formats/UnifiedNativeAdView#setIconView(android.view.View)

Example of stacktrace:
`Fatal Exception: java.lang.ClassCastException: com.nativeads.views.IconAdView cannot be cast to android.widget.ImageView
       at com.google.ads.mediation.facebook.FacebookAdapter$UnifiedAdMapper.trackViews(FacebookAdapter.java:932)
       at com.google.android.gms.internal.ads.zzaoo.zzc(zzaoo.java:62)
       at com.google.android.gms.internal.ads.zzanl.zza(zzanl.java:88)
       at com.google.android.gms.internal.ads.zzgv.onTransact(zzgv.java:13)
       at android.os.Binder.transact(Binder.java:949)
       at fx.aW(fx.java:2)
       at com.google.android.gms.ads.internal.mediation.client.r.x(r.java)
       at com.google.android.gms.ads.nonagon.ad.nativead.ck.a(ck.java:25)
       at com.google.android.gms.ads.nonagon.ad.nativead.aj.h(aj.java:4)
       at com.google.android.gms.ads.nonagon.ad.nativead.ag.run(ag.java)
       at android.os.Handler.handleCallback(Handler.java:883)`

So I think it is better to check class and use another FB registerViewForInteraction method without icon ImageView if icon is not actually ImageView, for example
`registerViewForInteraction(View view, MediaView mediaView, @Nullable List<View> clickableViews) `

**Comment by joshuajplagonera** [comment]
Hi @alexskobozev ,

Thanks for reporting this. We have pushed out a commit to help resolve this issue here: https://github.com/googleads/googleads-mobile-android-mediation/commit/37a6efdbba815c52f1a3ed4c0e5b9ed763dc4b63
It should be out with the next version of the adapter.

**Comment by joshuajplagonera** [comment]
Hi @alexskobozev , 
This fix should be live on version 6.3.0.1 of the Facebook Android adapter: https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/facebook/CHANGELOG.md#6301

Let us know if you are still experiencing this issue.
