### ISSUE TITLE
mopub crash after update to com.google.android.gms:play-services-ads:20.0.0

### ISSUE THREAD

**Issue by brunopiovan** [googleads/googleads-mobile-android-mediation#327]
I updated my dependency to com.google.android.gms:play-services-ads:20.0.0 and I started seeing a lot of crashes being logged, so I had to disable mopub.

This version of my app is using com.google.android.gms:play-services-ads:20.0.0 and com.google.ads.mediation:mopub:5.15.0.1.

I updated it to use 'com.google.ads.mediation:mopub:5.16.3.0' but that does not fix the issue.

```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method getHeight()I in class Lcom/mopub/mobileads/dfp/adapters/MoPubNativeMappedImage; or its super classes (declaration of 'com.mopub.mobileads.dfp.adapters.MoPubNativeMappedImage' appears in /data/app/com.-------1/base.apk)
       at com.mopub.mobileads.dfp.adapters.MoPubUnifiedNativeAdMapper.<init>(MoPubUnifiedNativeAdMapper.java)
       at com.mopub.mobileads.dfp.adapters.MoPubAdapter$1$1.onDownloadSuccess(MoPubAdapter.java:3)
       at com.mopub.mobileads.dfp.adapters.DownloadDrawablesAsync.onPostExecute(DownloadDrawablesAsync.java:1)
       at android.os.AsyncTask.finish(AsyncTask.java:667)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6165)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by stefanpledl** [comment]
Is this fixed in 20.1.0 ?

**Comment by joshuajplagonera** [comment]
Hi @brunopiovan and @stefanpledl ,

Can you try updating to version `5.17.0.0` of the MoPub Android adapter? I can confirm that I can see the crash ,but updating to 5.17.0.0 helped resolve the issue.

**Comment by brunopiovan** [comment]
hi,
I updated to `5.17.0.0` and play-services-ads to `20.2.0` and I can confirm it doesn't crash anymore.
