### ISSUE TITLE
Calling MobileAds.initialize(this) leads to the StrictMode policy violation

### ISSUE THREAD

**Issue by antonsakvelon** [googleads/googleads-mobile-android-mediation#355]
Hello.
I'm facing a StrictMode policy violation when trying to initialize MobileAds. Here's the stack trace:
```
D/StrictMode: StrictMode policy violation; ~duration=317 ms: android.os.strictmode.CustomViolation: gcore.dynamite
        at android.os.StrictMode$AndroidBlockGuardPolicy.onCustomSlowCall(StrictMode.java:1563)
        at android.os.StrictMode.noteSlowCall(StrictMode.java:2555)
        at unl.a(:com.google.android.gms@212621049@21.26.21 (150700-387928701):0)
        at com.google.android.gms.chimera.container.GmsModuleChimeraProvider.query(:com.google.android.gms@212621049@21.26.21 (150700-387928701):10)
        at rvr.query(:com.google.android.gms@212621049@21.26.21 (150700-387928701):3)
        at android.content.ContentProvider.query(ContentProvider.java:1379)
        at efl.superQuery(:com.google.android.gms@212621049@21.26.21 (150700-387928701):2)
        at com.google.android.chimera.ContentProvider.query(:com.google.android.gms@212621049@21.26.21 (150700-387928701):2)
        at rvr.query(:com.google.android.gms@212621049@21.26.21 (150700-387928701):8)
        at android.content.ContentProvider.query(ContentProvider.java:1475)
        at efl.superQuery(:com.google.android.gms@212621049@21.26.21 (150700-387928701):1)
        at com.google.android.chimera.ContentProvider.query(:com.google.android.gms@212621049@21.26.21 (150700-387928701):1)
        at efl.query(:com.google.android.gms@212621049@21.26.21 (150700-387928701):2)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:278)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
    # via Binder call with stack:
        at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2358)
        at android.os.Parcel.readExceptionCode(Parcel.java:2318)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:139)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
        at android.content.ContentResolver.query(ContentResolver.java:1183)
        at android.content.ContentResolver.query(ContentResolver.java:1115)
        at android.content.ContentResolver.query(ContentResolver.java:1071)
        at com.google.android.gms.dynamite.DynamiteModule.zzb(com.google.android.gms:play-services-basement@@17.6.0:10)
        at com.google.android.gms.dynamite.DynamiteModule.zza(com.google.android.gms:play-services-basement@@17.6.0:43)
        at com.google.android.gms.dynamite.DynamiteModule.getRemoteVersion(com.google.android.gms:play-services-basement@@17.6.0:1)
        at com.google.android.gms.internal.ads.zzbeu.zzd(com.google.android.gms:play-services-ads-lite@@20.3.0:5)
        at com.google.android.gms.internal.ads.zzbhv.zzw(com.google.android.gms:play-services-ads-lite@@20.3.0:3)
        at com.google.android.gms.internal.ads.zzbhv.zzb(com.google.android.gms:play-services-ads-lite@@20.3.0:8)
        at com.google.android.gms.ads.MobileAds.initialize(com.google.android.gms:play-services-ads-lite@@20.3.0:3)
        at com.MyApplication.onCreate(MyApplication.kt:76)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
The issue reproduces on emulators: Pixel 4, API 30 & Nexus 5, API 26 and on real device: Nokia 6.1, API 29

**Comment by joshuajplagonera** [comment]
Hi @antonsakvelon ,

I tried creating a fresh Nexus 5 emulator on my end with API 26 and I am not able to replicate this issue. Can you confirm which SDK version you are using? Additionally, can you check if  you can replicate this on [our sample apps](https://github.com/googleads/googleads-mobile-android-examples) ?

**Comment by joshh-devrel** [comment]
The strict mode violation came from the Google Mobile Ads SDK instead of mediation.
@antonsakvelon Please update to use the latest Google Mobile Ads SDK version and [contact](https://developers.google.com/admob/android/support) the corresponding support team if the issue still persists.
