### ISSUE TITLE
AdColony error on google automated tests

### ISSUE THREAD

**Issue by kenumir** [googleads/googleads-mobile-android-mediation#368]
Its happen only on automated tests when i upload app to Play Store. No errors from real devices.

Stack trace:
```
java.lang.ClassCastException: android.webkit.WebMessagePortWrapper cannot be cast to qz0
        at qz0.b(chromium-SystemWebViewGoogle.aab-stable-460608501:3)
        at com.android.webview.chromium.WebViewChromium.postMessageToMainFrame(chromium-SystemWebViewGoogle.aab-stable-460608501:3)
        at android.webkit.WebView.postWebMessage(WebView.java:1880)
        at com.adcolony.sdk.w0.e(w0:18)
        at com.adcolony.sdk.w0.d(w0:3)
        at com.adcolony.sdk.w0$b.onPageFinished(w0:2)
        at nC0.b(chromium-SystemWebViewGoogle.aab-stable-460608501:2)
        at ka.handleMessage(chromium-SystemWebViewGoogle.aab-stable-460608501:62)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5421)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Device:
```
brand: google
manufacturer: LGE
model: Nexus 5X
osVersion: 6.0.1
osBuild: MTC20F
```

Firebase-Ads: `com.google.firebase:firebase-ads:20.4.0`
AdColony mediation adapter: `com.google.ads.mediation:adcolony:4.6.3.0`

**Comment by vikram731** [comment]
I am also seeing the same issue. +1

**Comment by agramonte** [comment]
Same here. +1

**Comment by UtsavG93** [comment]
same here. +1

**Comment by Paitomax** [comment]
same here. +1

**Comment by pabloleban** [comment]
same here. +1

**Comment by naumenkopeter** [comment]
same here. +1

**Comment by valikblazhko** [comment]
+1

**Comment by joshuajplagonera** [comment]
Hi All,

Looking at the stack trace of the error, it looks like an AdColony SDK specific issue. I would suggest reaching out to the AdColony team regarding this error.

**Comment by heknt** [comment]
+1

**Comment by bylbaboy** [comment]
+1

**Comment by shefich** [comment]
Same for me.
`Caused by java.lang.ClassCastException
android.webkit.WebMessagePortWrapper cannot be cast to lA0
lA0.b (chromium-SystemWebViewGoogle.aab-stable-466410401:3)
com.android.webview.chromium.WebViewChromium.postMessageToMainFrame (chromium-SystemWebViewGoogle.aab-stable-466410401:3)
android.webkit.WebView.postWebMessage (WebView.java:1880)
com.adcolony.sdk.w0.e (SourceFile:18)
com.adcolony.sdk.w0.d (SourceFile:3)
com.adcolony.sdk.w0$b.onPageFinished (SourceFile:2)
jD0.b (chromium-SystemWebViewGoogle.aab-stable-466410401:2)
ha.handleMessage (chromium-SystemWebViewGoogle.aab-stable-466410401:62)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5421)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)`

**Comment by tfkci** [comment]
+1

**Comment by dfpalomar** [comment]
Same here. Detected in OnePlus8Pro

**Comment by Tom3652** [comment]
my live users are affected by this issue.

**Comment by mtrezza** [comment]
Observed on OnePlus8Pro with Android 11

**Comment by auvehassan** [comment]
same as @mtrezza, Device: OnePlus8Pro - android 11 - rooted

Fatal Exception: java.lang.ClassCastException: android.webkit.WebMessagePortWrapper cannot be cast to Ap0
       at Ap0.b(Ap0.java:3)
       at com.android.webview.chromium.WebViewChromium.postMessageToMainFrame(WebViewChromium.java:3)
       at android.webkit.WebView.postWebMessage_aroundBody14(WebView.java:1979)
       at android.webkit.WebView$AjcClosure15.run(WebView.java:1)
       at org.mojitoaspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
       at com.mojito.framework.WebView.logPostWebMessage(WebView.java:301)
       at android.webkit.WebView.postWebMessage(WebView.java:1978)
       at com.adcolony.sdk.c1.d(SourceFile:16)
       at com.adcolony.sdk.c1.c(SourceFile:2)
       at com.adcolony.sdk.c1$j.a(SourceFile:3)
       at com.adcolony.sdk.c1$g.safedk_c1$g_onPageFinished_5ac446337541d274fdc47859d66f0200(SourceFile:2)
       at com.adcolony.sdk.c1$g.onPageFinished(SourceFile:12)
       at com.adcolony.sdk.j$e.safedk_j$e_onPageFinished_08730707c7c7e937de2d01674f0cebb1(SourceFile:1)
       at com.adcolony.sdk.j$e.onPageFinished(SourceFile:12)
       at com.adcolony.sdk.l$e.safedk_l$e_onPageFinished_d5ecf758fa8b837c0c6445e7f4010c01(SourceFile:2)
       at com.adcolony.sdk.l$e.onPageFinished(SourceFile:12)
       at ss0.b(ss0.java:2)
       at q8.handleMessage(q8.java:61)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by legz** [comment]
+1 same crash here, detected on OnePlus8Pro (and a suite similar crash on Nexus 5X)

**Comment by reachvineetjain** [comment]
+1 Have it on a Nexus 5x Android 6

**Comment by RiverboatGambler** [comment]
+1

12 Crashes from 6 Users: all OnePlus8Pro, Android 11

**Comment by ntduc-let** [comment]
+ 1

**Comment by ntduc-let** [comment]
+1 Have it on a Nexus 5X Android 6.0.1

**Comment by ChuckWalters** [comment]
+1

**Comment by Robiullah2244** [comment]
Same here for Nexus 5X (6.0.1)

**Comment by Gabriel9Stresser** [comment]
+1
android12
Galaxy A22

**Comment by ClenildoCardoso** [comment]
> Observed on OnePlus8Pro with Android 11, apparently only affecting testing during the Google Play pre-launch report.

I am also receiving this report. And as you said, it is only the pre-launch because if you filter on the most recent dates you will no longer receive these errors.
