### ISSUE TITLE
AppLovinMediationAdapter NullPointerException when loading Rewarded ad

### ISSUE THREAD

**Issue by avi-cramer** [googleads/googleads-mobile-android-mediation#422]
A customer reported an issue where Rewarded ads would not load whenever they first load the app. We located the source of the issue being [L295 of the AppLovinMediationAdapter ](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/applovin/applovin/src/main/java/com/google/ads/mediation/applovin/AppLovinMediationAdapter.java#L295), when `preload` is called immediately after the AppLovin SDK is initialized. The `NullPointerException` is due to `mIncentivizedInterstitial` not being initialized until the callback `onInitializeSuccess` but L295 get called before that. Simple fix would be to move L295 to take place after `mIncentivizedInterstitial` is initialized within the `onInitializeSuccess` callback.

```
E/Ads: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.applovin.adview.AppLovinIncentivizedInterstitial.preload(com.applovin.sdk.AppLovinAdLoadListener)' on a null object reference
        at com.google.ads.mediation.applovin.AppLovinMediationAdapter.loadRewardedAd(AppLovinMediationAdapter.java:295)
        at com.google.android.gms.internal.ads.zzbyg.zzz(com.google.android.gms:play-services-ads-lite@@20.6.0:13)
        at com.google.android.gms.internal.ads.zzbxj.zzbQ(com.google.android.gms:play-services-ads-lite@@20.6.0:48)
        at com.google.android.gms.internal.ads.zzaok.onTransact(com.google.android.gms:play-services-ads-base@@20.6.0:3)
        at android.os.Binder.transact(Binder.java:1043)
        at ady.be(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:2)
        at com.google.android.gms.ads.internal.mediation.client.e.t(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:0)
        at com.google.android.gms.ads.nonagon.render.cp.b(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:9)
        at com.google.android.gms.ads.nonagon.render.dp.a(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:0)
        at com.google.android.gms.ads.nonagon.util.concurrent.s.call(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:0)
        at boc.a(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:0)
        at bnl.run(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:3)
        at bod.run(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:0)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at arc.a(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:0)
        at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:1)
        at arc.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:0)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by joshh-devrel** [comment]
The NPE issue is fixed in AppLovin adapter version `11.5.3.1`.
