### ISSUE TITLE
Get crash with mediation applovin 11.4.0.0+

### ISSUE THREAD

**Issue by Nghicv** [googleads/googleads-mobile-android-mediation#462]
FATAL EXCEPTION: main
                                                                                                    Process: snapedit.app.remove.Stag, PID: 4413
                                                                                                    java.lang.VerifyError: Verifier rejected class ab.d91: java.lang.Object ab.d91.F() failed to verify: java.lang.Object ab.d91.F(): [0x30] register v3 has type Reference: java.lang.Object but expected Reference: androidx.appcompat.widget.m (declaration of 'ab.d91' appears in /data/app/snapedit.app.remove.Stag-2/base.apk:classes2.dex)
                                                                                                    	at ab.ej0.<init>(SourceFile:423)
                                                                                                    	at ab.dj0.c(SourceFile:4)
                                                                                                    	at ab.rp1.a(SourceFile:55)
                                                                                                    	at ab.sg1.S0(SourceFile:18)
                                                                                                    	at ab.sg1.b4(SourceFile:3)
                                                                                                    	at ab.c00.f(SourceFile:2)
                                                                                                    	at z9.a.b(SourceFile:13)
                                                                                                    	at snapedit.app.remove.repository.AdsService.l(SourceFile:9)
                                                                                                    	at cn.j.s(SourceFile:5)
                                                                                                    	at ui.a.h(SourceFile:3)
                                                                                                    	at lj.r0.run(SourceFile:18)
                                                                                                    	at lj.x0.Z0(SourceFile:8)
                                                                                                    	at lj.y0.Y0(SourceFile:1)
                                                                                                    	at lj.h.c(SourceFile:14)
                                                                                                    	at rl.a.a(SourceFile)
                                                                                                    	at cm.j.r(SourceFile:4)
                                                                                                    	at cn.m.t(SourceFile:4)
                                                                                                    	at cn.g.s(SourceFile:53)
                                                                                                    	at ui.a.h(SourceFile:3)
                                                                                                    	at ab.m41.g(SourceFile:10)
                                                                                                    	at lj.m.t(SourceFile:15)
                                                                                                    	at lj.m.F(SourceFile:6)
                                                                                                    	at lj.m.h(SourceFile:4)
                                                                                                    	at cn.b.a(SourceFile:1)
                                                                                                    	at w9.s2.q3(SourceFile:15)
                                                                                                    	at ab.wl.run(SourceFile:5)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    	at ab.qy1.a(SourceFile:1)
                                                                                                    	at y9.b1.a(SourceFile:1)
                                                                                                    	at ab.qy1.dispatchMessage(SourceFile:1)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                                                    	Suppressed: lj.p0: [y1{Cancelling}@9e98318, Dispatchers.Main.immediate]

**Comment by joshh-devrel** [comment]
The provided stack trace doesn't show the issue is either coming from AppLovin SDK or Google Mobile Ads SDK.

Would need the following information to proceed: GMA SDK version, adapter version, full stack trace, reproducing steps and sample project.
