### ISSUE TITLE
Firebase Crash issue: java.lang.ClassCastException: android.webkit.WebMessagePortWrapper cannot be cast to Zz0

### ISSUE THREAD

**Issue by jinjin-lee** [googleads/googleads-mobile-android-mediation#484]
Fatal Exception: java.lang.ClassCastException: android.webkit.WebMessagePortWrapper cannot be cast to Zz0
       at Zz0.b(chromium-SystemWebViewGoogle.aab-stable-463807401:3)
       at com.android.webview.chromium.WebViewChromium.postMessageToMainFrame(chromium-SystemWebViewGoogle.aab-stable-463807401:3)
       at android.webkit.WebView.postWebMessage(WebView.java:1880)
       at com.adcolony.sdk.c1.d(SourceFile:16)
       at com.adcolony.sdk.c1.c(SourceFile:2)
       at com.adcolony.sdk.c1$j.a(SourceFile:3)
       at com.adcolony.sdk.c1$e.onPageFinished(SourceFile:2)
       at com.adcolony.sdk.j$c.onPageFinished(SourceFile:1)
       at com.adcolony.sdk.l$c.onPageFinished(SourceFile:2)
       at XC0.b(chromium-SystemWebViewGoogle.aab-stable-463807401:2)
       at na.handleMessage(chromium-SystemWebViewGoogle.aab-stable-463807401:62)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Hello
I am getting above crash error from firebase frequently.
But I cannot found reason well.
Please help me the reason of above crash issue.
Thanks

I am using follwoing version
'com.google.ads.mediation:facebook:6.15.0.0'
'com.google.ads.mediation:adcolony:4.8.0.2'

**Comment by joshh-devrel** [comment]
@jinjin-lee Seems like the crash came from the AdColony SDK so I would suggest reaching to the AdColony team for next steps.
