### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'int android.os.Bundle.size()' on a null object reference

### ISSUE THREAD

**Issue by rahullraghuwanshi** [googleads/googleads-mobile-android-mediation#485]
Getting lot of crashes in xiaomi devices only. Below are the details : 

Device Name : Redmi Note 10S
Operating System : Android 13

`
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.size()' on a null object reference
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
       at android.os.Parcel.createException(Parcel.java:2995)
       at android.os.Parcel.readException(Parcel.java:2978)
       at android.os.Parcel.readException(Parcel.java:2920)
       at android.view.IWindowManager$Stub$Proxy.getSupportedDisplayHashAlgorithms(IWindowManager.java:5532)
       at android.view.displayhash.DisplayHashManager.getSupportedHashAlgorithms(DisplayHashManager.java:71)
       at com.google.android.gms.ads.eventattestation.internal.l.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:33)
       at com.google.android.gms.ads.nonagon.ad.j.e(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:247)
       at com.google.android.gms.ads.nonagon.ad.g.run(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)`

**Comment by NVentimiglia** [comment]
Hi @rahullraghuwanshi can you provide some more details?

- which version of google ads are you using?
- what mediation packages are in use?
- do you have any replication steps and a sample application?
- do you have a complete stack trace or charles log?

**Comment by rahullraghuwanshi** [comment]
Hi @NVentimiglia 

Here are the details :

- Google ads version : 22.2.0
- No we are not using any mediation package we are using.
- No we are not able to reproduce this error only able to get.

`Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.DisplayHashController.getDisplayHashAlgorithms(DisplayHashController.java:250)
	at com.android.server.wm.DisplayHashController.getSupportedHashAlgorithms(DisplayHashController.java:145)
	at com.android.server.wm.WindowManagerService.getSupportedDisplayHashAlgorithms(WindowManagerService.java:9818)
	at android.view.IWindowManager$Stub.onTransact(IWindowManager.java:3180)
	at com.android.server.wm.WindowManagerService.onTransact(WindowManagerService.java:1600)`

**Comment by NVentimiglia** [comment]
Hi @rahullraghuwanshi 


It is pretty hard to diagnose issues without replication steps. Can you open up a support case on https://groups.google.com/g/google-admob-ads-sdk ? This request will be sent over to the SDK team which is better equipped to solve this specific issue.
