### ISSUE TITLE
NPE com.facebook.ads.NativeAd$Rating.getValue

### ISSUE THREAD

**Issue by progimax** [googleads/googleads-mobile-android-mediation#62]
We use facebook audience network with Admob Mediation.
Sometimes we have a fatal exception when we try to show a native ad.

`
E/AndroidRuntime: FATAL EXCEPTION: main
Process: ***, PID: 28511
java.lang.NullPointerException: Attempt to invoke virtual method 'double com.facebook.ads.internal.n.g.a()' on a null object reference
at com.facebook.ads.NativeAd$Rating.getValue(Unknown Source)
at com.google.ads.mediation.facebook.FacebookAdapter$AppInstallMapper.getRating(FacebookAdapter.java:967)
at com.google.ads.mediation.facebook.FacebookAdapter$AppInstallMapper.mapNativeAd(FacebookAdapter.java:787)
at com.google.ads.mediation.facebook.FacebookAdapter$NativeListener.onAdLoaded(FacebookAdapter.java:623)
at com.facebook.ads.NativeAd$1.a(Unknown Source)
at com.facebook.ads.internal.n.e$1$1.c(Unknown Source)
at com.facebook.ads.internal.n.e$1$1.a(Unknown Source)
at com.facebook.ads.internal.d.b$1$2.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:836)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:203)
at android.app.ActivityThread.main(ActivityThread.java:6247)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
`

**Comment by rajendrachauhan** [comment]
I also using facebook audience network with Admob Mediation.
Sometime i get FATAL Exception in main Process - NullpointerException as given above same as issue.
when using show native ad only.
please solve issue.

**Comment by progimax** [comment]
The issue will be solve in the next release of Facebook Audience Network.

<img width="702" alt="capture d ecran 2018-03-28 a 11 35 44" src="https://user-images.githubusercontent.com/4715927/38021266-adc7635c-327c-11e8-8295-d1fafe60de1a.png">
