### ISSUE TITLE
i am getting this exception in my fabric 

### ISSUE THREAD

**Issue by Mateeen** [googleads/googleads-mobile-android-mediation#85]
`Fatal Exception: java.lang.IllegalStateException: Must setVideoReportUri first.
       at com.facebook.ads.internal.view.n.setVideoMPD(Unknown Source)
       at com.facebook.ads.MediaViewVideoRenderer.setNativeAd(Unknown Source)
       at com.facebook.ads.internal.view.e.setNativeAd(Unknown Source)
       at com.facebook.ads.MediaView.setNativeAd(Unknown Source)
       at com.google.ads.mediation.facebook.FacebookAdapter$AppInstallMapper.mapNativeAd(FacebookAdapter.java:774)
       at com.google.ads.mediation.facebook.FacebookAdapter$NativeListener.onAdLoaded(FacebookAdapter.java:623)
       at com.facebook.ads.NativeAd$1.a(Unknown Source)
       at com.facebook.ads.internal.n.e$1$1.c(Unknown Source)
       at com.facebook.ads.internal.n.e$1$1.a(Unknown Source)
       at com.facebook.ads.internal.d.b$1$2.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

**Comment by samlu** [comment]
My apps report the exactly same exception.

**Comment by yamsergey** [comment]
+1 here

**Comment by spilaka** [comment]
Yes, try with updated version 4.28.1.

**Comment by samlu** [comment]
The crash errors only happened for 1 day and seem to be fixed OTA. Should be okay to move to the resolved state.
