### ISSUE TITLE
MopubAdapter - : java.lang.ClassCastException

### ISSUE THREAD

**Issue by elrufoelrufo** [googleads/googleads-mobile-android-mediation#97]
Hello, 

I'm getting the following error with Mopub when trying to show an interstitial by Admob Mediation. Please, could you have a look into this?  

Error  log : 

> 10-11 13:27:05.450 13661-13661/com.radiofmapp.radiocanada D/DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
> 10-11 13:27:05.465 13661-13661/com.radiofmapp.radiocanada I/Ads: Starting ad request.
>     SDK version: afma-sdk-a-v14366037.13000000.1
> 10-11 13:27:05.467 13661-13661/com.radiofmapp.radiocanada I/Ads: Use AdRequest.Builder.addTestDevice("XXXXXXXXXXXXXXXXXX") to get test ads on this device.
> 10-11 13:27:05.510 13661-14145/com.radiofmapp.radiocanada I/Ads: Trying mediation network: garbage
> 10-11 13:27:05.511 13661-13661/com.radiofmapp.radiocanada I/Ads: Instantiating mediation adapter: com.mopub.mobileads.dfp.adapters.MoPubAdapter
> 10-11 13:27:05.513 13661-13661/com.radiofmapp.radiocanada W/Ads: Server parameters: {"adUnitId":"XXXXXXXXXXXXXXXXXX"}
> 10-11 13:27:05.514 13661-13661/com.radiofmapp.radiocanada E/Ads: java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Activity
>         at com.mopub.mobileads.dfp.adapters.MoPubAdapter.requestInterstitialAd(MoPubAdapter.java:442)
>         at com.google.android.gms.internal.ads.zzzk.zza(Unknown Source:63)
>         at com.google.android.gms.internal.ads.zzyr.dispatchTransaction(Unknown Source:71)
>         at com.google.android.gms.internal.ads.zzen.onTransact(Unknown Source:12)
>         at android.os.Binder.transact(Binder.java:667)
>         at mp.b(:com.google.android.gms.dynamite_adsdynamite@14366081@14.3.66 (100400-213742215):15)
>         at com.google.android.gms.ads.internal.mediation.client.g.a(:com.google.android.gms.dynamite_adsdynamite@14366081@14.3.66 (100400-213742215):41)
>         at com.google.android.gms.ads.internal.mediation.g.run(:com.google.android.gms.dynamite_adsdynamite@14366081@14.3.66 (100400-213742215):46)
>         at android.os.Handler.handleCallback(Handler.java:898)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at com.google.android.gms.ads.internal.util.e.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@14366081@14.3.66 (100400-213742215):5)
>         at android.os.Looper.loop(Looper.java:198)
>         at android.app.ActivityThread.main(ActivityThread.java:6716)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 10-11 13:27:05.514 13661-13661/com.radiofmapp.radiocanada W/Ads: Could not request ad from mediation adapter.
>     android.os.RemoteException
>         at com.google.android.gms.internal.ads.zzzk.zza(Unknown Source:67)
>         at com.google.android.gms.internal.ads.zzyr.dispatchTransaction(Unknown Source:71)
>         at com.google.android.gms.internal.ads.zzen.onTransact(Unknown Source:12)
>         at android.os.Binder.transact(Binder.java:667)
>         at mp.b(:com.google.android.gms.dynamite_adsdynamite@14366081@14.3.66 (100400-213742215):15)
>         at com.google.android.gms.ads.internal.mediation.client.g.a(:com.google.android.gms.dynamite_adsdynamite@14366081@14.3.66 (100400-213742215):41)
>         at com.google.android.gms.ads.internal.mediation.g.run(:com.google.android.gms.dynamite_adsdynamite@14366081@14.3.66 (100400-213742215):46)
>         at android.os.Handler.handleCallback(Handler.java:898)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at com.google.android.gms.ads.internal.util.e.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@14366081@14.3.66 (100400-213742215):5)
>         at android.os.Looper.loop(Looper.java:198)
>         at android.app.ActivityThread.main(ActivityThread.java:6716)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 10-11 13:27:05.515 13661-14145/com.radiofmapp.radiocanada I/Ads: No fill from any mediation ad networks.
> 10-11 13:27:05.516 13661-13661/com.radiofmapp.radiocanada W/Ads: Failed to load ad: 3
> 10-11 13:27:05.804 13661-14144/com.radiofmapp.radiocanada W/Ads: Received non-success response code 302 from pinging URL: http://google.com
>

**Comment by spilaka** [comment]
@elrufoelrufo Are you still facing the issue ?

**Comment by elrufoelrufo** [comment]
Hello,

I can resolve this issue.   I'm getting this error when ondestroy is called. Do you know how to unregister Mopub receiver when ondestroy is called ?  

**Error LOG:**

> 2018-10-23 16:46:46.711 25163-25163/com.google.android.gms.example.interstitialexample E/ActivityThread: Activity com.google.android.gms.example.interstitialexample.MyActivity has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@5cc3f that was originally registered here. Are you missing a call to unregisterReceiver()?
>     android.app.IntentReceiverLeaked: Activity com.google.android.gms.example.interstitialexample.MyActivity has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@5cc3f that was originally registered here. Are you missing a call to unregisterReceiver()?
>         at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1429)
>         at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1210)
>         at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1488)
>         at android.app.ContextImpl.registerReceiver(ContextImpl.java:1461)
>         at android.app.ContextImpl.registerReceiver(ContextImpl.java:1449)
>  

I have reported this issue more than one month ago in the following google group : 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/google-admob-ads-sdk/q5uB90FYk0g/mmo_bdOSAAAJ
 
Thanks. Regards.

**Comment by spilaka** [comment]
@elrufoelrufo I can look into that. Can you share me testapp which reproduces the same issue ? So we can debug the issue.
Thanks.

**Comment by elrufoelrufo** [comment]
Yes, sure. I'm using MoPubInterstitialSample.You can download it in the conversation in google admob ads sdk group. If you can't download it, please, let me know how I can share it with you. 

Thanks for your help.
